// Generated by scripts/gen-api-routes.mjs. Do not edit.
import * as r0 from "../endpoints/account/me_GET";
import * as r1 from "../endpoints/auth/forgot_POST";
import * as r2 from "../endpoints/auth/session_GET";
import * as r3 from "../endpoints/billing/checkout_POST";
import * as r4 from "../endpoints/billing/manage_POST";
import * as r5 from "../endpoints/billing/overview_GET";
import * as r6 from "../endpoints/billing/portal_POST";
import * as r7 from "../endpoints/billing/refresh_POST";
import * as r8 from "../endpoints/billing/return_GET";
import * as r9 from "../endpoints/billing/status_GET";
import * as r10 from "../endpoints/catalog/delete_POST";
import * as r11 from "../endpoints/catalog/save_POST";
import * as r12 from "../endpoints/clients/delete_POST";
import * as r13 from "../endpoints/clients/save_POST";
import * as r14 from "../endpoints/crew/delete_POST";
import * as r15 from "../endpoints/crew/save_POST";
import * as r16 from "../endpoints/crm/authorize_POST";
import * as r17 from "../endpoints/crm/callback_GET";
import * as r18 from "../endpoints/crm/disconnect_POST";
import * as r19 from "../endpoints/crm/pipelines_GET";
import * as r20 from "../endpoints/crm/pull_POST";
import * as r21 from "../endpoints/crm/settings_POST";
import * as r22 from "../endpoints/crm/status_GET";
import * as r23 from "../endpoints/crm/webhook_POST";
import * as r24 from "../endpoints/embed_GET";
import * as r25 from "../endpoints/gbp/manage_POST";
import * as r26 from "../endpoints/gbp/status_GET";
import * as r27 from "../endpoints/gcal/authorize_POST";
import * as r28 from "../endpoints/gcal/callback_GET";
import * as r29 from "../endpoints/gcal/disconnect_POST";
import * as r30 from "../endpoints/gcal/status_GET";
import * as r31 from "../endpoints/gcal/sync_POST";
import * as r32 from "../endpoints/gocardless/callback_GET";
import * as r33 from "../endpoints/gocardless/connect_POST";
import * as r34 from "../endpoints/gocardless/status_GET";
import * as r35 from "../endpoints/gocardless/webhook_POST";
import * as r36 from "../endpoints/invites/info_GET";
import * as r37 from "../endpoints/jobs/photo_POST";
import * as r38 from "../endpoints/jobs/save_POST";
import * as r39 from "../endpoints/jobs/send_invoice_POST";
import * as r40 from "../endpoints/jobs/work_POST";
import * as r41 from "../endpoints/leadform/get_GET";
import * as r42 from "../endpoints/leadform/save_POST";
import * as r43 from "../endpoints/onboarding/apply_POST";
import * as r44 from "../endpoints/onboarding/complete_POST";
import * as r45 from "../endpoints/ops/snapshot_GET";
import * as r46 from "../endpoints/payments/check_POST";
import * as r47 from "../endpoints/payments/dd_POST";
import * as r48 from "../endpoints/payments/link_POST";
import * as r49 from "../endpoints/payments/sync_POST";
import * as r50 from "../endpoints/public/doc_GET";
import * as r51 from "../endpoints/public/invoice_dd_POST";
import * as r52 from "../endpoints/public/invoice_pay_POST";
import * as r53 from "../endpoints/public/lead_form_GET";
import * as r54 from "../endpoints/public/lead_submit_POST";
import * as r55 from "../endpoints/public/lead_upload_POST";
import * as r56 from "../endpoints/public/quote_respond_POST";
import * as r57 from "../endpoints/public/review_optout_GET";
import * as r58 from "../endpoints/quotes/book_POST";
import * as r59 from "../endpoints/quotes/save_POST";
import * as r60 from "../endpoints/quotes/send_POST";
import * as r61 from "../endpoints/settings/save_POST";
import * as r62 from "../endpoints/square/callback_GET";
import * as r63 from "../endpoints/square/connect_POST";
import * as r64 from "../endpoints/square/status_GET";
import * as r65 from "../endpoints/square/webhook_POST";
import * as r66 from "../endpoints/stripe/authorize_POST";
import * as r67 from "../endpoints/stripe/billing_webhook_POST";
import * as r68 from "../endpoints/stripe/callback_GET";
import * as r69 from "../endpoints/stripe/check_POST";
import * as r70 from "../endpoints/stripe/disconnect_POST";
import * as r71 from "../endpoints/stripe/link_POST";
import * as r72 from "../endpoints/stripe/status_GET";
import * as r73 from "../endpoints/stripe/webhook_POST";
import * as r74 from "../endpoints/team/invite_POST";
import * as r75 from "../endpoints/team/list_GET";
import * as r76 from "../endpoints/team/revoke_POST";
import * as r77 from "../endpoints/xero/callback_GET";
import * as r78 from "../endpoints/xero/connect_POST";
import * as r79 from "../endpoints/xero/status_GET";
import * as r80 from "../endpoints/xero/webhook_POST";

export const routes: Record<string, { handle: (request: Request) => Promise<Response> | Response }> = {
  "GET account/me": r0,
  "POST auth/forgot": r1,
  "GET auth/session": r2,
  "POST billing/checkout": r3,
  "POST billing/manage": r4,
  "GET billing/overview": r5,
  "POST billing/portal": r6,
  "POST billing/refresh": r7,
  "GET billing/return": r8,
  "GET billing/status": r9,
  "POST catalog/delete": r10,
  "POST catalog/save": r11,
  "POST clients/delete": r12,
  "POST clients/save": r13,
  "POST crew/delete": r14,
  "POST crew/save": r15,
  "POST crm/authorize": r16,
  "GET crm/callback": r17,
  "POST crm/disconnect": r18,
  "GET crm/pipelines": r19,
  "POST crm/pull": r20,
  "POST crm/settings": r21,
  "GET crm/status": r22,
  "POST crm/webhook": r23,
  "GET embed": r24,
  "POST gbp/manage": r25,
  "GET gbp/status": r26,
  "POST gcal/authorize": r27,
  "GET gcal/callback": r28,
  "POST gcal/disconnect": r29,
  "GET gcal/status": r30,
  "POST gcal/sync": r31,
  "GET gocardless/callback": r32,
  "POST gocardless/connect": r33,
  "GET gocardless/status": r34,
  "POST gocardless/webhook": r35,
  "GET invites/info": r36,
  "POST jobs/photo": r37,
  "POST jobs/save": r38,
  "POST jobs/send_invoice": r39,
  "POST jobs/work": r40,
  "GET leadform/get": r41,
  "POST leadform/save": r42,
  "POST onboarding/apply": r43,
  "POST onboarding/complete": r44,
  "GET ops/snapshot": r45,
  "POST payments/check": r46,
  "POST payments/dd": r47,
  "POST payments/link": r48,
  "POST payments/sync": r49,
  "GET public/doc": r50,
  "POST public/invoice_dd": r51,
  "POST public/invoice_pay": r52,
  "GET public/lead_form": r53,
  "POST public/lead_submit": r54,
  "POST public/lead_upload": r55,
  "POST public/quote_respond": r56,
  "GET public/review_optout": r57,
  "POST quotes/book": r58,
  "POST quotes/save": r59,
  "POST quotes/send": r60,
  "POST settings/save": r61,
  "GET square/callback": r62,
  "POST square/connect": r63,
  "GET square/status": r64,
  "POST square/webhook": r65,
  "POST stripe/authorize": r66,
  "POST stripe/billing_webhook": r67,
  "GET stripe/callback": r68,
  "POST stripe/check": r69,
  "POST stripe/disconnect": r70,
  "POST stripe/link": r71,
  "GET stripe/status": r72,
  "POST stripe/webhook": r73,
  "POST team/invite": r74,
  "GET team/list": r75,
  "POST team/revoke": r76,
  "GET xero/callback": r77,
  "POST xero/connect": r78,
  "GET xero/status": r79,
  "POST xero/webhook": r80,
};
