// Bundles the API (app/server/edge.ts + app/endpoints + app/helpers) into one ESM file for the
// `api` Supabase Edge Function (Deno). npm packages are bundled in; Node built-ins become node:*.
//   node scripts/build-api.mjs           → supabase/functions/api/index.js
//   node scripts/build-api.mjs --dev OUT → local runner with a storage stub (app/server/dev.ts)
import { build } from "esbuild";
import { builtinModules } from "node:module";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

const dev = process.argv.includes("--dev");
// --npm-external: leave npm packages as npm: imports for Supabase's Deno runtime to fetch,
// which keeps the uploaded file small (used when deploying through the Supabase API).
const npmExternal = process.argv.includes("--npm-external");
const pkgVersion = (name) => JSON.parse(readFileSync(new URL(`../node_modules/${name}/package.json`, import.meta.url))).version;
const NPM = ["kysely", "kysely-postgres-js", "postgres", "zod", "superjson", "nanoid"];
const outfile = dev ? process.argv[process.argv.indexOf("--dev") + 1] : "supabase/functions/api/index.js";
const stub = fileURLToPath(new URL("../app/server/browserOnlyStub.ts", import.meta.url));
const builtins = new Set(builtinModules.flatMap((m) => [m, `node:${m}`]));

const result = await build({
  entryPoints: [dev ? "app/server/dev.ts" : "app/server/edge.ts"],
  outfile,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "es2022",
  minify: !dev,
  sourcemap: false,
  legalComments: "none",
  metafile: true,
  banner: {
    js: [
      "// Generated by scripts/build-api.mjs from app/. Do not edit.",
      'import { createRequire as __hsoCreateRequire } from "node:module";',
      'import __hsoProcess from "node:process";',
      'import { Buffer as __hsoBuffer } from "node:buffer";',
      'import { setImmediate as __hsoSetImmediate, clearImmediate as __hsoClearImmediate } from "node:timers";',
      // import.meta.url is https:// when the bundle is imported remotely; createRequire needs a file URL.
      "const require = __hsoCreateRequire(\"file:///hso-api.js\");",
      "globalThis.process ??= __hsoProcess;",
      "globalThis.Buffer ??= __hsoBuffer;",
      // Supabase's Edge Runtime has no global setImmediate; the postgres driver uses it.
      "globalThis.setImmediate ??= __hsoSetImmediate;",
      "globalThis.clearImmediate ??= __hsoClearImmediate;",
    ].join("\n"),
  },
  plugins: [
    {
      name: "hso-server",
      setup(b) {
        // Browser-only modules imported by shared *.schema.ts files.
        b.onResolve({ filter: /helpers\/(apiFetch|supabaseClient)$/ }, () => ({ path: stub }));
        if (npmExternal)
          b.onResolve({ filter: /^[a-z@][^:]*$/ }, (args) => {
            const name = NPM.find((n) => args.path === n || args.path.startsWith(`${n}/`));
            return name ? { path: `npm:${name}@${pkgVersion(name)}${args.path.slice(name.length)}`, external: true } : undefined;
          });
        // Deno needs the node: prefix on built-ins.
        b.onResolve({ filter: /^[a-z:_/]+$/ }, (args) =>
          builtins.has(args.path) ? { path: args.path.startsWith("node:") ? args.path : `node:${args.path}`, external: true } : undefined,
        );
      },
    },
  ],
});

const inputs = Object.keys(result.metafile.inputs);
const leaked = inputs.filter((p) => /node_modules\/(react|react-dom|@supabase\/supabase-js|lucide-react)\//.test(p));
if (leaked.length) {
  console.error("Browser code leaked into the API bundle:", leaked.slice(0, 5));
  process.exit(1);
}
const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
console.log(`${outfile}: ${(bytes / 1024).toFixed(0)} KB from ${inputs.length} modules`);
